---

k3s_config:

  data_dir: /data/platform/kubernetes/k3s

  disable:
    - traefik

  kube_apiserver:
    event_ttl: 1h

  kubelet:
    max_pods: 110
    container_log_max_size: 10Mi
    container_log_max_files: 5
