# ansible/roles/k3s/defaults/main.yaml
---
# triggering config rollout to clean up disabled components
k3s_version: "v1.33.1+k3s1"
k3s_data_dir: /data/platform/kubernetes/k3s
k3s_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
k3s_install: true
k3s_config_only: false

k3s_config:
  data_dir: /data/platform/kubernetes/k3s
  disable:
    - traefik
  kube_apiserver:
    event_ttl: 1h
  kubelet:
    max_pods: 110
    container_log_max_size: 10Mi
    container_log_max_files: 5
