---

- name: Get installed K3s version
  ansible.builtin.command:
    cmd: k3s --version
  register: k3s_installed_version
  failed_when: false
  changed_when: false

- name: Download K3s installer
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: "0755"

- name: Install or upgrade K3s
  ansible.builtin.command:
    cmd: /bin/bash /tmp/k3s-install.sh
  changed_when: true
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: >-
      server --cluster-init
      --config /etc/rancher/k3s/config.yaml
  when:
    - not k3s_config_only
    - k3s_installed_version.rc != 0 or
      k3s_version not in k3s_installed_version.stdout
  notify:
    - Restart K3s

- name: Enable K3s service
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started

- name: Wait for K3s service
  ansible.builtin.systemd:
    name: k3s
    state: started
  register: k3s_service
  retries: 10
  delay: 15
  until: k3s_service.status.ActiveState == "active"

- name: Wait for K3s node token
  ansible.builtin.wait_for:
    path: "{{ k3s_data_dir }}/server/node-token"
    timeout: 300

- name: Verify K3s node
  ansible.builtin.command:
    cmd: kubectl --kubeconfig {{ k3s_kubeconfig_path }} get nodes
  register: k3s_nodes
  changed_when: false

- name: Display node status
  ansible.builtin.debug:
    var: k3s_nodes.stdout_lines
