---
- name: Ensure kube directory exists
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Check kubeconfig exists
  ansible.builtin.stat:
    path: /home/ubuntu/.kube/config
  register: k3s_kubeconfig_file

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: "{{ k3s_kubeconfig_path }}"
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: "0600"
