---

- name: Setup storage
  ansible.builtin.import_tasks: storage.yaml

- name: Validate storage
  ansible.builtin.import_tasks: validate_disk.yaml

- name: Install prerequisites
  ansible.builtin.import_tasks: prereqs.yaml

- name: Install K3s
  ansible.builtin.import_tasks: install.yaml

- name: Configure kubeconfig
  ansible.builtin.import_tasks: kubeconfig.yaml
