# ansible/roles/k3s/tasks/main.yaml
---
- name: Ensure storage is ready
  ansible.builtin.include_tasks: storage.yaml
  when: not k3s_config_only

- name: Validate disk
  import_tasks: validate_disk.yaml

- name: Install prerequisites
  ansible.builtin.include_tasks: prereqs.yaml
  when: not k3s_config_only

- name: Install or upgrade K3s
  ansible.builtin.include_tasks: install.yaml
  when: not k3s_config_only

- name: Apply or update K3s configuration
  import_tasks: config-rollout.yaml

- name: Configure logging
  import_tasks: logging.yaml

- name: Configure cleanup jobs
  import_tasks: cleanup.yaml

- name: Setup kubeconfig
  import_tasks: kubeconfig.yaml