---
- name: Install K3s dependencies
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - ca-certificates
      - apt-transport-https
      - gnupg
      - software-properties-common
    state: present
    update_cache: true

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable bridge nftables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: true
