---
#

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-config
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adityac1305@gmail.com          # <-- Replace with your email
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: lab-gateway
                namespace: envoy-gateway-system
                kind: Gateway
