---

name: Ansible Lint

on:
  pull_request:
    paths:
      - "ansible/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: |
          ansible-lint ansible/playbooks/os-bootstrap.yml
