---

name: Ansible Validate

on:
  pull_request:
    paths:
      - "ansible/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Use project ansible.cfg
        run: echo "ANSIBLE_CONFIG=ansible/ansible.cfg" >> $GITHUB_ENV

      - name: Syntax check OS bootstrap
        run: |
          ansible-playbook \
            -i ansible/inventories/lab/hosts.ini \
            ansible/playbooks/os-bootstrap.yml \
            --syntax-check

      - name: Syntax check K3s
        run: |
          ansible-playbook \
            -i ansible/inventories/lab/hosts.ini \
            ansible/playbooks/k3s-bootstrap.yml \
            --syntax-check
