---

name: OpenTofu Validate

on:
  pull_request:
    paths:
      - "opentofu/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: opentofu/environments/lab

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init (no backend)
        run: tofu init -backend=false

      - name: Format check
        run: tofu fmt -check -recursive

      - name: Validate
        run: tofu validate